### ISSUE TITLE
Big Sur issues

### ISSUE THREAD

**Issue by erikng** [pinterest/it-cpe-cookbooks#26]
there's probably more

```
================================================================================
Recipe Compile Error
================================================================================

Chef::Exceptions::RecipeNotFound
--------------------------------
could not find recipe macos for cookbook cpe_firewall

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/cpe_firewall/recipes/default.rb:14:in `from_file'
  /var/chef/cache/cookbooks/cpe_uber_init/recipes/default.rb:268:in `block in from_file'
  /var/chef/cache/cookbooks/cpe_uber_init/recipes/default.rb:267:in `each'
  /var/chef/cache/cookbooks/cpe_uber_init/recipes/default.rb:267:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/cpe_firewall/recipes/default.rb:

  7:  # Copyright (c) 2017-present, Pinterest, Inc.
  8:  # All rights reserved.
  9:  #
 10:  # This source code is licensed under the Apache 2.0 license found in the
 11:  # LICENSE file in the root directory of this source tree.
 12:  #
 13:  
 14>> include_recipe "cpe_firewall::#{node['platform']}"
 15:  

System Info:
------------
chef_version=16.1.16
platform=macos
platform_version=10.16
ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin17]
program_name=/usr/local/bin/chef-client
executable=/opt/chef/bin/chef-client


Running handlers:
[2020-06-22T17:46:51-07:00] ERROR: Running exception handlers
Running handlers complete
[2020-06-22T17:46:51-07:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 19 seconds
[2020-06-22T17:46:51-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2020-06-22T17:46:51-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-06-22T17:46:51-07:00] FATAL: Chef::Exceptions::RecipeNotFound: could not find recipe macos for cookbook cpe_firewall
```

```
Generated at 2020-06-22 17:46:51 -0700
Chef::Exceptions::RecipeNotFound: could not find recipe macos for cookbook cpe_firewall
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/cookbook_version.rb:204:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context.rb:393:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context.rb:349:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context.rb:348:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context.rb:348:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/cpe_firewall/recipes/default.rb:14:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/cookbook_version.rb:230:in `load_ruby_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/cookbook_version.rb:200:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context.rb:393:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context.rb:349:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context.rb:348:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context.rb:348:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/cpe_uber_init/recipes/default.rb:268:in `block in from_file'
/var/chef/cache/cookbooks/cpe_uber_init/recipes/default.rb:267:in `each'
/var/chef/cache/cookbooks/cpe_uber_init/recipes/default.rb:267:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/cookbook_version.rb:230:in `load_ruby_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/cookbook_version.rb:200:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context.rb:393:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context/cookbook_compiler.rb:174:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context/cookbook_compiler.rb:171:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context/cookbook_compiler.rb:171:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context/cookbook_compiler.rb:79:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/run_context.rb:223:in `load'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/policy_builder/expand_node_object.rb:103:in `setup_run_context'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/client.rb:498:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application.rb:292:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application.rb:268:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application.rb:251:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.1.16/bin/chef-client:25:in `<top (required)>'
/usr/local/bin/chef-client:171:in `load'
/usr/local/bin/chef-client:171:in `<main>'
```

**Comment by erikng** [comment]
those issues are gone, but we all need to guard our profile calls to below macOS 11

**Comment by 1dustindavis** [comment]
Yeah, but that should probably be handled by `cpe_profiles` throwing warnings

**Comment by erikng** [comment]
Maybe. I think what's more likely is a bifrucation of what cpe_profiles becomes.
